name: matter_dart
description: A Flutter-friendly 2D rigid-body physics engine inspired by Matter.js, written in Dart.
version: 1.0.0
homepage: https://github.com/rajajain08/matter-dart
repository: https://github.com/rajajain08/matter-dart
issue_tracker: https://github.com/rajajain08/matter-dart/issues
topics:
  - physics
  - flutter
  - matterjs
  - simulation
  - game-development

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter.
flutter:
